### ISSUE TITLE
Corteza Docker - unable to start the containers

### ISSUE THREAD

**Issue by martin1551** [cortezaproject/corteza-server#105] opened 2020-08-14 13:22 UTC
I tried to install corteza docker containers according to the official HowTo guide. 
https://docs.cortezaproject.org/corteza-docs/2020.6/maint/index.html#install

I have my docker up and running on Ubuntu 18.04.5 LTS with other cointainers happily running. 

The problem is with corteza_correador cointainer - I see it as unhealthy. 

This is in its log:   

```
{"level":30,"time":1597409924933,"name":"check","msg":"server-scripts service configured","v":1}
{"level":30,"time":1597409924946,"name":"check","output":"/tmp/corredor/bundler-dist","msg":"making bundler output directory","v":1}
{"level":30,"time":1597409924956,"name":"services.dependencies","msg":"initializing watcher","v":1}
{"level":30,"time":1597409925027,"name":"services.server-scripts","searchPaths":["/extensions/*","/corredor/usr/*","/corredor/usr"],"msg":"reloading server scripts","v":1}
{"level":30,"time":1597409925300,"name":"services.client-scripts","searchPaths":["/extensions/*","/corredor/usr/*","/corredor/usr"],"msg":"reloading client scripts","v":1}
{"level":30,"time":1597409929236,"name":"services.client-scripts","valid":19,"total":19,"msg":"processed","v":1}
{"level":30,"time":1597409936971,"name":"services.server-scripts","valid":14,"total":14,"msg":"processed","v":1}
{"level":30,"time":1597409937070,"name":"gRPC","msg":"server running at corredor:8082","v":1}
```

Also  corteza_server is stopped. 

```
{"level":"warn","ts":1597409907.093877,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":1,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409912.1021376,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":2,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409917.10366,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":3,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409922.1083221,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":4,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409927.11075,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":5,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409932.1142328,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":6,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409937.116536,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":7,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409942.1180427,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":8,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409947.1191387,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":9,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409952.1213322,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":10,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409957.1226094,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":11,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}
{"level":"warn","ts":1597409962.1240015,"logger":"database","caller":"db/connector.go:66","msg":"could not connect to the database","name":"default","error":"dial tcp 172.20.0.2:3306: connect: connection refused","errorVerbose":"dial tcp 172.20.0.2:3306: connect: connection refused\ngithub.com/titpetric/factory.(*DatabaseFactory).Get\n\t/drone/src/vendor/github.com/titpetric/factory/database.go:142\ngithub.com/cortezaproject/corteza-server/pkg/db.TryToConnect.func1\n\t/drone/src/pkg/db/connector.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","try":12,"dsn":"c****a:c****e@tcp(db:3306)/corteza?collation=utf8mb4_general_ci","delay":5}

Error: could not connect to database: db init for "default" timedout
```

I appreciate any help how to resolve this. 

Thank you

**Comment by requaos** [comment] 2020-08-19 20:26
Not a duplicate of #104 , as default percona image does not set sql_require_primary_key by default

**Comment by darh** [comment] 2020-08-19 21:43
@requaos I don't see how this is a duplicate?

@martin1551 can you check the db container and see what's going on there?

**Comment by martin1551** [comment] 2020-08-31 21:16
> 
> 
> @requaos I don't see how this is a duplicate?
> 
> @martin1551 can you check the db container and see what's going on there?

db container is healthy and running. Here you can see the log.

```
Initializing database,
2020-08-14T12:58:19.257892Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.20-11) initializing of server in progress as process 14,
2020-08-14T12:58:19.464728Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.,
2020-08-14T12:58:38.227358Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.,
2020-08-14T12:58:59.023528Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.,
Database initialized,
MySQL init process in progress...,
2020-08-14T12:59:47.314502Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.20-11) starting as process 75,
2020-08-14T12:59:47.382140Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.,
MySQL init process in progress...,
MySQL init process in progress...,
MySQL init process in progress...,
2020-08-14T12:59:50.160288Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.,
2020-08-14T12:59:50.887020Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/lib/mysql/mysqlx.sock',
MySQL init process in progress...,
MySQL init process in progress...,
2020-08-14T12:59:53.015878Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.,
2020-08-14T12:59:53.228786Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20-11'  socket: '/var/lib/mysql/mysql.sock'  port: 0  Percona Server (GPL), Release 11, Revision 5b5a5d2.,
mysql: [Warning] Using a password on the command line interface can be insecure.,
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.,
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.,
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.,
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.,
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.,
mysql: [Warning] Using a password on the command line interface can be insecure.,
mysql: [Warning] Using a password on the command line interface can be insecure.,
mysql: [Warning] Using a password on the command line interface can be insecure.,
mysql: [Warning] Using a password on the command line interface can be insecure.,
mysql: [Warning] Using a password on the command line interface can be insecure.,
,
2020-08-14T13:00:30.200211Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.20-11)  Percona Server (GPL), Release 11, Revision 5b5a5d2.,
,
MySQL init process done. Ready for start up.,
,
2020-08-14T13:00:30.734785Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.20-11) starting as process 1,
2020-08-14T13:00:30.747329Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.,
2020-08-14T13:00:32.443591Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.,
2020-08-14T13:00:32.908352Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/lib/mysql/mysqlx.sock' bind-address: '::' port: 33060,
2020-08-14T13:00:33.429211Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.,
2020-08-14T13:00:33.524183Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20-11'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  Percona Server (GPL), Release 11, Revision 5b5a5d2.,
```

**Comment by maciejflorczyk** [comment] 2020-09-21 13:42
Hello.
How exactly do you fix this? I'm having the same issue, but I'm not quite sure what's the proper fix/workaround?
```
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS                      PORTS                                      NAMES
d5567f0979e6        cortezaproject/corteza-webapp:2020.6            "/entrypoint.sh"         33 minutes ago      Up 33 minutes (healthy)     80/tcp                                     corteza_webapp_1
ba530fa3acda        cortezaproject/corteza-server-monolith:2020.6   "/corteza/bin/server…"   33 minutes ago      Up 33 minutes (unhealthy)   80/tcp                                     corteza_server_1
f83d93a9d82b        cortezaproject/corteza-server-corredor:2020.6   "/corredor/node_modu…"   33 minutes ago      Up 33 minutes (unhealthy)   80/tcp                                     corteza_corredor_1
be7bf626db04        percona:8.0                                     "/docker-entrypoint.…"   33 minutes ago      Up 33 minutes (healthy)     3306/tcp, 33060/tcp                        corteza_db_1
a4c34cc0f67b        jrcs/letsencrypt-nginx-proxy-companion          "/bin/bash /app/entr…"   39 minutes ago      Up 39 minutes                                                          nginx-letsencrypt
8ebfca840cbb        jwilder/nginx-proxy                             "/app/docker-entrypo…"   39 minutes ago      Up 39 minutes               0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-proxy

```

**Comment by darh** [comment] 2021-03-09 18:11
I'll close this. If this is still an issue, reopen.

**Closed as completed by darh** 2021-03-09 18:11 UTC
